#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from plp5.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 45 "plp5.y"


#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <iostream>
#include <vector>
#include <algorithm>
#include "comun.h"
#include <sstream>


using namespace std;

// variables y funciones del A. Léxico
extern int ncol,nlin,findefichero;

int nTempMin = 16000;
int nTempMax = 16384;
int nVarActual = 0;
int nTempActual = 16000;
//extern int tmp;
extern int yylex();
extern char *yytext;
extern FILE *yyin;


int yyerror(char *s);


int ptr_mem = 0;
int ptr_mem_temp = MAX_MEM+1;
int ptr_label = 0;

string operador, s1, s2;  // string auxiliares

typedef struct simbolo_t {
	string 	lexema;
	int 	tipo;
	int 	dir;
	bool 	esArray;
	int 	idTipo;
	int 	lin,col;
}simbolo;

typedef struct tipo_t {
    int tipo;
    int size;
    int tipo_base;
    tipo_t() : tipo(0), size(0)
    {}
}tipo;

struct find_simbolo : std::unary_function<simbolo_t, bool>
{
	std::string lexema;
	find_simbolo(std::string l):lexema(l){}
	bool operator()(simbolo_t const& s) const
	{ return s.lexema == lexema; }
};

typedef struct tabla_simbolos_t 
{
	const char* nombre;
	struct tabla_simbolos_t* ts_padre;
	std::vector<simbolo_t> simbolos;			
}tabla_simbolos;

simbolo_t* buscar_simbolo(const char* lexema); 
bool lexema_existe(const char* lexema);
void print_tabla_simbolos();
void crear_ambito(const char* nombre);
void destruir_ambito_actual();
void destroy();
int NTemp();
int getDir();
// Variables globales
struct tabla_simbolos_t* ambito;

string IntToString (int a)
{
    ostringstream temp;
    temp<<a;
    return temp.str();
}

// tabla simbolos
std::vector<simbolo_t> simbolos;
// tabla de tipos
vector<tipo> tabla_tipos;
// añadir simbolo a la tabla actual
void nuevoSimbolo(const char* lexema,const int& tipo, const int& dir, const bool& esArray, int idTipo,int nlin,int ncol);
//void nuevoSimbolo(simbolo_t& s, const int& tipo);
// recuperar simbolo por lexema (simbolo debe contener lexema al llamar a la funcion)
bool buscarSimbolo(simbolo_t& simbolo); 
// True si el simbolo ya esta declarado
bool existeSimbolo(string &simbolo);

int NTemp();
// Devuelve el struct de un tipo
bool buscarTipo(int tipo_buscado, tipo_t& t);
// Inicializa tabla tipos con los basicos
void inicializarTablaTipos();
// añade un tipo array la tabla de tipos
void nuevoTipo(const int& tam, const int& tipo);
// Pasa un string a minusculas
void toLower(string& str);

bool esBase(int tipo);


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	boolean_	258
#define	int_	259
#define	double_	260
#define	main_	261
#define	system_	262
#define	out_	263
#define	in_	264
#define	println_	265
#define	print_	266
#define	string_	267
#define	class_	268
#define	import_	269
#define	new_	270
#define	public_	271
#define	static_	272
#define	void_	273
#define	scanner_	274
#define	nextInt_	275
#define	nextDouble_	276
#define	if_	277
#define	else_	278
#define	while_	279
#define	true_	280
#define	false_	281
#define	coma_	282
#define	pyc_	283
#define	punto_	284
#define	pari_	285
#define	pard_	286
#define	relop_	287
#define	addop_	288
#define	mulop_	289
#define	asig_	290
#define	cori_	291
#define	cord_	292
#define	llavei_	293
#define	llaved_	294
#define	and_	295
#define	or_	296
#define	not_	297
#define	nentero	298
#define	nreal	299
#define	id	300


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int boolean_;
static const int int_;
static const int double_;
static const int main_;
static const int system_;
static const int out_;
static const int in_;
static const int println_;
static const int print_;
static const int string_;
static const int class_;
static const int import_;
static const int new_;
static const int public_;
static const int static_;
static const int void_;
static const int scanner_;
static const int nextInt_;
static const int nextDouble_;
static const int if_;
static const int else_;
static const int while_;
static const int true_;
static const int false_;
static const int coma_;
static const int pyc_;
static const int punto_;
static const int pari_;
static const int pard_;
static const int relop_;
static const int addop_;
static const int mulop_;
static const int asig_;
static const int cori_;
static const int cord_;
static const int llavei_;
static const int llaved_;
static const int and_;
static const int or_;
static const int not_;
static const int nentero;
static const int nreal;
static const int id;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,boolean_=258
	,int_=259
	,double_=260
	,main_=261
	,system_=262
	,out_=263
	,in_=264
	,println_=265
	,print_=266
	,string_=267
	,class_=268
	,import_=269
	,new_=270
	,public_=271
	,static_=272
	,void_=273
	,scanner_=274
	,nextInt_=275
	,nextDouble_=276
	,if_=277
	,else_=278
	,while_=279
	,true_=280
	,false_=281
	,coma_=282
	,pyc_=283
	,punto_=284
	,pari_=285
	,pard_=286
	,relop_=287
	,addop_=288
	,mulop_=289
	,asig_=290
	,cori_=291
	,cord_=292
	,llavei_=293
	,llaved_=294
	,and_=295
	,or_=296
	,not_=297
	,nentero=298
	,nreal=299
	,id=300


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::boolean_=258;
const int YY_parse_CLASS::int_=259;
const int YY_parse_CLASS::double_=260;
const int YY_parse_CLASS::main_=261;
const int YY_parse_CLASS::system_=262;
const int YY_parse_CLASS::out_=263;
const int YY_parse_CLASS::in_=264;
const int YY_parse_CLASS::println_=265;
const int YY_parse_CLASS::print_=266;
const int YY_parse_CLASS::string_=267;
const int YY_parse_CLASS::class_=268;
const int YY_parse_CLASS::import_=269;
const int YY_parse_CLASS::new_=270;
const int YY_parse_CLASS::public_=271;
const int YY_parse_CLASS::static_=272;
const int YY_parse_CLASS::void_=273;
const int YY_parse_CLASS::scanner_=274;
const int YY_parse_CLASS::nextInt_=275;
const int YY_parse_CLASS::nextDouble_=276;
const int YY_parse_CLASS::if_=277;
const int YY_parse_CLASS::else_=278;
const int YY_parse_CLASS::while_=279;
const int YY_parse_CLASS::true_=280;
const int YY_parse_CLASS::false_=281;
const int YY_parse_CLASS::coma_=282;
const int YY_parse_CLASS::pyc_=283;
const int YY_parse_CLASS::punto_=284;
const int YY_parse_CLASS::pari_=285;
const int YY_parse_CLASS::pard_=286;
const int YY_parse_CLASS::relop_=287;
const int YY_parse_CLASS::addop_=288;
const int YY_parse_CLASS::mulop_=289;
const int YY_parse_CLASS::asig_=290;
const int YY_parse_CLASS::cori_=291;
const int YY_parse_CLASS::cord_=292;
const int YY_parse_CLASS::llavei_=293;
const int YY_parse_CLASS::llaved_=294;
const int YY_parse_CLASS::and_=295;
const int YY_parse_CLASS::or_=296;
const int YY_parse_CLASS::not_=297;
const int YY_parse_CLASS::nentero=298;
const int YY_parse_CLASS::nreal=299;
const int YY_parse_CLASS::id=300;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		150
#define	YYFLAG		-32768
#define	YYNTBASE	46

#define YYTRANSLATE(x) ((unsigned)(x) <= 300 ? yytranslate[x] : 74)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     8,     9,    13,    17,    19,    26,    38,    40,
    42,    44,    49,    52,    53,    54,    59,    60,    70,    82,
    86,    89,    94,    98,    99,   100,   106,   108,   109,   112,
   115,   116,   118,   120,   125,   135,   145,   151,   159,   165,
   169,   171,   175,   177,   181,   183,   187,   189,   193,   195,
   197,   203,   209,   211,   213,   215,   217,   221,   224,   229,
   231,   232
};

static const short yyrhs[] = {    47,
    49,     0,    47,    14,    48,    28,     0,     0,    48,    29,
    45,     0,    48,    29,    19,     0,    45,     0,    16,    13,
    45,    38,    50,    39,     0,    16,    17,    18,     6,    30,
    12,    36,    37,    45,    31,    52,     0,     4,     0,     5,
     0,     3,     0,    38,    53,    64,    39,     0,    53,    54,
     0,     0,     0,    51,    55,    59,    28,     0,     0,    51,
    57,    45,    35,    15,    51,    56,    58,    28,     0,    19,
    45,    35,    15,    19,    30,     7,    29,     9,    31,    28,
     0,    57,    36,    37,     0,    36,    37,     0,    36,    43,
    37,    58,     0,    36,    43,    37,     0,     0,     0,    60,
    59,    27,    61,    62,     0,    62,     0,     0,    63,    45,
     0,    64,    65,     0,     0,    28,     0,    52,     0,    72,
    35,    66,    28,     0,     7,    29,     8,    29,    10,    30,
    66,    31,    28,     0,     7,    29,     8,    29,    11,    30,
    66,    31,    28,     0,    22,    30,    66,    31,    65,     0,
    22,    30,    66,    31,    65,    23,    65,     0,    24,    30,
    66,    31,    65,     0,    66,    41,    67,     0,    67,     0,
    67,    40,    68,     0,    68,     0,    69,    32,    69,     0,
    69,     0,    69,    33,    70,     0,    70,     0,    70,    34,
    71,     0,    71,     0,    72,     0,    45,    29,    20,    30,
    31,     0,    45,    29,    21,    30,    31,     0,    43,     0,
    44,     0,    25,     0,    26,     0,    30,    66,    31,     0,
    42,    71,     0,    30,    51,    31,    66,     0,    45,     0,
     0,    72,    36,    73,    69,    37,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   160,   168,   172,   176,   180,   184,   188,   193,   198,   206,
   214,   224,   229,   232,   236,   236,   243,   243,   258,   262,
   265,   269,   277,   283,   283,   283,   289,   294,   294,   302,
   305,   308,   311,   314,   317,   320,   323,   327,   331,   335,
   338,   342,   345,   349,   352,   356,   359,   363,   366,   370,
   373,   376,   379,   385,   391,   397,   403,   406,   409,   413,
   422,   423
};

static const char * const yytname[] = {   "$","error","$illegal.","boolean_",
"int_","double_","main_","system_","out_","in_","println_","print_","string_",
"class_","import_","new_","public_","static_","void_","scanner_","nextInt_",
"nextDouble_","if_","else_","while_","true_","false_","coma_","pyc_","punto_",
"pari_","pard_","relop_","addop_","mulop_","asig_","cori_","cord_","llavei_",
"llaved_","and_","or_","not_","nentero","nreal","id","S","Import","SecImp","Class",
"Main","Tipo","Bloque","BDecl","DVar","@1","@2","DimSN","Dimensiones","LIdent",
"@3","@4","Variable","@5","SeqInstr","Instr","Expr","EConj","ERel","Esimple",
"Term","Factor","Ref","@6",""
};
#endif

static const short yyr1[] = {     0,
    46,    47,    47,    48,    48,    48,    49,    50,    51,    51,
    51,    52,    53,    53,    55,    54,    56,    54,    54,    57,
    57,    58,    58,    60,    61,    59,    59,    63,    62,    64,
    64,    65,    65,    65,    65,    65,    65,    65,    65,    66,
    66,    67,    67,    68,    68,    69,    69,    70,    70,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    72,
    73,    72
};

static const short yyr2[] = {     0,
     2,     4,     0,     3,     3,     1,     6,    11,     1,     1,
     1,     4,     2,     0,     0,     4,     0,     9,    11,     3,
     2,     4,     3,     0,     0,     5,     1,     0,     2,     2,
     0,     1,     1,     4,     9,     9,     5,     7,     5,     3,
     1,     3,     1,     3,     1,     3,     1,     3,     1,     1,
     5,     5,     1,     1,     1,     1,     3,     2,     4,     1,
     0,     5
};

static const short yydefact[] = {     3,
     0,     0,     0,     1,     6,     0,     0,     2,     0,     0,
     5,     4,     0,     0,     0,     0,     7,     0,     0,     0,
     0,     0,     0,     0,     0,    14,     8,    31,    11,     9,
    10,     0,    15,    13,     0,     0,     0,    24,     0,     0,
     0,     0,    32,    12,    60,    33,    30,     0,     0,    21,
     0,    24,    27,     0,     0,     0,     0,     0,     0,     0,
    61,     0,    16,     0,    29,    20,     0,     0,    55,    56,
     0,     0,    53,    54,    60,     0,    41,    43,    45,    47,
    49,    50,     0,     0,     0,     0,    25,     0,     0,     0,
     0,    58,     0,     0,     0,     0,     0,     0,     0,     0,
    34,     0,     0,    28,    17,     0,     0,     0,    57,     0,
     0,    37,    40,    42,    44,    46,    48,    39,    62,     0,
    26,     0,     0,     0,    59,     0,     0,     0,     0,     0,
     0,     0,     0,    51,    52,    38,     0,     0,    18,     0,
     0,     0,    23,    35,    36,    19,    22,     0,     0,     0
};

static const short yydefgoto[] = {   148,
     1,     6,     4,    15,    33,    46,    28,    34,    38,   122,
    39,   131,    51,    52,   104,    53,    54,    35,    47,    76,
    77,    78,    79,    80,    81,    82,    85
};

static const short yypact[] = {-32768,
    66,   -28,    55,-32768,-32768,    27,   -21,-32768,    -8,    43,
-32768,-32768,    74,    72,    52,    76,-32768,    86,    65,    84,
    61,    62,    53,    69,    63,-32768,-32768,    44,-32768,-32768,
-32768,    57,    68,-32768,    -6,    70,    71,-32768,    24,    77,
    79,    80,-32768,-32768,-32768,-32768,-32768,    26,    88,-32768,
    83,-32768,-32768,    78,    81,    82,    99,    28,    28,    28,
-32768,    93,-32768,    87,-32768,-32768,    98,    90,-32768,-32768,
     1,    28,-32768,-32768,    91,   -16,    85,-32768,    51,    92,
-32768,    94,   -11,   -18,    28,    97,-32768,    73,    75,   100,
    -3,-32768,    67,    12,    28,    28,    28,    28,    28,    12,
-32768,    42,   108,-32768,-32768,   102,   103,    28,-32768,   104,
   105,   101,    85,-32768,    89,    92,-32768,-32768,-32768,   107,
-32768,   106,    28,    28,    96,   109,   110,    12,   112,    95,
   111,    11,    33,-32768,-32768,-32768,   113,   114,-32768,   115,
   117,   118,   106,-32768,-32768,-32768,-32768,   116,   128,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,   -59,   122,-32768,-32768,-32768,-32768,
-32768,   -14,   119,-32768,-32768,    45,-32768,-32768,   -87,   -57,
    58,    54,   -76,    50,   -64,   -35,-32768
};


#define	YYLAST		171


static const short yytable[] = {    48,
    40,    83,    84,    29,    30,    31,   112,    92,   102,   101,
    11,    90,   118,    91,    94,    41,     5,    42,    40,   100,
   115,    43,    95,    10,    95,    69,    70,   109,   105,    95,
    71,    26,    44,    41,   117,    42,    12,    95,    45,    43,
   136,   140,    72,    73,    74,    75,    29,    30,    31,    26,
   125,    95,    69,    70,     8,     9,    45,    71,    48,    55,
    60,    61,    32,   141,    48,   132,   133,     7,    56,    72,
    73,    74,    75,    95,    98,    29,    30,    31,   119,     2,
    13,     3,    97,    98,   106,   107,   110,   111,    16,    14,
    17,    19,    48,    18,    20,    21,    22,    24,    23,    25,
    26,    36,    62,    37,    49,    57,    68,    50,    58,    59,
    63,    86,    88,    87,   120,   149,    67,    66,    89,    93,
   137,    98,    65,   128,    96,    99,   103,   150,   147,    61,
   108,   123,   124,   126,   127,   129,    95,   138,   139,   134,
   135,   130,   144,   142,   145,   146,    27,   116,   121,   114,
   143,     0,   113,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    64
};

static const short yycheck[] = {    35,
     7,    59,    60,     3,     4,     5,    94,    72,    85,    28,
    19,    71,   100,    71,    31,    22,    45,    24,     7,    31,
    97,    28,    41,    45,    41,    25,    26,    31,    88,    41,
    30,    38,    39,    22,    99,    24,    45,    41,    45,    28,
   128,    31,    42,    43,    44,    45,     3,     4,     5,    38,
   108,    41,    25,    26,    28,    29,    45,    30,    94,    36,
    35,    36,    19,    31,   100,   123,   124,    13,    45,    42,
    43,    44,    45,    41,    33,     3,     4,     5,    37,    14,
    38,    16,    32,    33,    10,    11,    20,    21,    17,    16,
    39,     6,   128,    18,    30,    12,    36,    45,    37,    31,
    38,    45,    15,    36,    35,    29,     8,    37,    30,    30,
    28,    19,    15,    27,     7,     0,    35,    37,    29,    29,
     9,    33,    45,    23,    40,    34,    30,     0,   143,    36,
    31,    30,    30,    30,    30,    29,    41,    43,    28,    31,
    31,    36,    28,    31,    28,    28,    25,    98,   104,    96,
    37,    -1,    95,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    52
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 160 "plp5.y"
{
	yyval.cod = yyvsp[-1].cod + yyvsp[0].cod;
	print_tabla_simbolos();
						int tk = yylex();
                        if (tk != 0) yyerror("");
                        cout << yyvsp[0].cod << endl;
;
    break;}
case 2:
#line 168 "plp5.y"
{
	yyval.cod = yyvsp[-3].cod + yyvsp[-1].cod;
	//No hace nada?
;
    break;}
case 3:
#line 172 "plp5.y"
{
	//No hace nada?
	   ;
    break;}
case 4:
#line 176 "plp5.y"
{
	yyval.cod = yyvsp[-2].cod;
		//No hace nada?
;
    break;}
case 5:
#line 180 "plp5.y"
{
	    	yyval.cod = yyvsp[-2].cod;
	//No hace nada?
	   ;
    break;}
case 6:
#line 184 "plp5.y"
{
	//No hace nada?
	   ;
    break;}
case 7:
#line 188 "plp5.y"
{
		//No hace nada?
	yyval.cod = yyvsp[-1].cod;
;
    break;}
case 8:
#line 193 "plp5.y"
{
		//No hace nada?
	yyval.cod = yyvsp[0].cod;
;
    break;}
case 9:
#line 198 "plp5.y"
{
		int tmp = NTemp();
		yyval.dir = tmp;
		yyval.nlin = nlin;
		yyval.ncol = ncol;
		yyval.tipo = ENTERO;

	;
    break;}
case 10:
#line 206 "plp5.y"
{
		
		int tmp = NTemp();
		yyval.dir = tmp;
		yyval.tipo = REAL;
		yyval.nlin = nlin;
		yyval.ncol = ncol;
	 ;
    break;}
case 11:
#line 214 "plp5.y"
{

	  	int tmp = NTemp();
		yyval.dir = tmp;
		yyval.tipo = BOOLEANO;
		yyval.nlin = nlin;
		yyval.ncol = ncol;

	 ;
    break;}
case 12:
#line 224 "plp5.y"
{
	
	yyval.cod = yyvsp[-3].cod;
;
    break;}
case 13:
#line 229 "plp5.y"
{
	yyval.cod = yyvsp[-1].cod;
;
    break;}
case 14:
#line 232 "plp5.y"
{
	  
	  ;
    break;}
case 15:
#line 236 "plp5.y"
{yyval.tipo = yyvsp[0].tipo; ;
    break;}
case 16:
#line 236 "plp5.y"
{

    int tmp = NTemp();
    yyval.dir = tmp;
    yyval.tipo = yyvsp[-3].tipo;
    
    ;
    break;}
case 17:
#line 243 "plp5.y"
{yyval.tipo = yyvsp[-5].tipo;
    break;}
case 18:
#line 243 "plp5.y"
{

      if(esBase(yyvsp[-1].tipo))
      {
        int tmp = NTemp();
        yyval.dir = tmp;
        yyval.tipo = yyvsp[-8].tipo;
        nuevoSimbolo(yyvsp[-6].lexema,yyvsp[-8].tipo, tmp, true, yyvsp[-1].tipo, nlin, ncol-strlen(yytext));

    }else
    {
      msgError(ERRDIM, nlin, ncol, "");
      }

   ;
    break;}
case 19:
#line 258 "plp5.y"
{

   ;
    break;}
case 20:
#line 262 "plp5.y"
{
  
;
    break;}
case 21:
#line 265 "plp5.y"
{

    ;
    break;}
case 22:
#line 269 "plp5.y"
{
    
    int tmp = NTemp();
    yyval.dir = tmp;
    yyval.tipo = yyvsp[-4].tipo;
    //No hace falta cod porque es una declaración, las operacioens de cod se harán cuando se acceda a lectura de los arrays. NOP?
    nuevoTipo(yyvsp[-2].lexema, yyvsp[-4].tipo);
;
    break;}
case 23:
#line 277 "plp5.y"
{
        int tmp = NTemp();
        yyval.dir = tmp;
        yyval.tipo = yyvsp[-3].tipo;
        nuevoTipo(yyvsp[-1].lexema, yyvsp[-3].tipo);
      ;
    break;}
case 24:
#line 283 "plp5.y"
{yyval.tipo = yyvsp[0].tipo;;
    break;}
case 25:
#line 283 "plp5.y"
{yyval.tipo = yyvsp[-3].tipo;;
    break;}
case 26:
#line 283 "plp5.y"
{

	int tmp = NTemp();
	yyval.dir = tmp;
	
	;
    break;}
case 27:
#line 289 "plp5.y"
{
	   	yyval = yyvsp[0];

	   ;
    break;}
case 28:
#line 294 "plp5.y"
{yyval.tipo = yyvsp[0].tipo;;
    break;}
case 29:
#line 294 "plp5.y"
{

	int tmp = NTemp();
	yyval.dir = tmp;
	nuevoSimbolo(yyvsp[0].lexema,VARIABLE, tmp, false, yyvsp[-2].tipo );

;
    break;}
case 30:
#line 302 "plp5.y"
{
	yyval.cod = yyvsp[-1].cod + yyvsp[0].cod;
;
    break;}
case 31:
#line 305 "plp5.y"
{
		 ;
    break;}
case 32:
#line 308 "plp5.y"
{
	
;
    break;}
case 33:
#line 311 "plp5.y"
{

	  ;
    break;}
case 34:
#line 314 "plp5.y"
{

	  ;
    break;}
case 35:
#line 317 "plp5.y"
{

	  ;
    break;}
case 36:
#line 320 "plp5.y"
{

	  ;
    break;}
case 37:
#line 323 "plp5.y"
{

	  	yyval.cod = yyvsp[-2].cod + "\nmov " + IntToString(yyvsp[-2].dir) + "A\njz " + IntToString(yyvsp[0].dir) + "\n" + yyvsp[0].cod;
	  ;
    break;}
case 38:
#line 327 "plp5.y"
{

	  	yyval.cod = yyvsp[-4].cod + "\nmov " + IntToString(yyvsp[-4].dir) + "A\njz " + IntToString(yyvsp[-2].dir) + "\n" + yyvsp[-2].cod + "\njmp " + IntToString(yyvsp[0].dir) + yyvsp[0].cod;
	  ;
    break;}
case 39:
#line 331 "plp5.y"
{
	  	yyval.cod = yyvsp[-2].cod + "mov " + IntToString(yyvsp[-2].dir) + " A\njz " + IntToString(yyvsp[0].dir) + "\n" + yyvsp[0].cod + "\njmp " + IntToString(yyvsp[-2].dir);
	  ;
    break;}
case 40:
#line 335 "plp5.y"
{

;
    break;}
case 41:
#line 338 "plp5.y"
{

	 ;
    break;}
case 42:
#line 342 "plp5.y"
{
	
;
    break;}
case 43:
#line 345 "plp5.y"
{

	  ;
    break;}
case 44:
#line 349 "plp5.y"
{
	
;
    break;}
case 45:
#line 352 "plp5.y"
{

	 ;
    break;}
case 46:
#line 356 "plp5.y"
{
	
;
    break;}
case 47:
#line 359 "plp5.y"
{

		;
    break;}
case 48:
#line 363 "plp5.y"
{
	
;
    break;}
case 49:
#line 366 "plp5.y"
{

	 ;
    break;}
case 50:
#line 370 "plp5.y"
{
	
;
    break;}
case 51:
#line 373 "plp5.y"
{

	   ;
    break;}
case 52:
#line 376 "plp5.y"
{

	   ;
    break;}
case 53:
#line 379 "plp5.y"
{
	   		int tmp 	= NTemp();
	   		yyval.tipo = ENTERO;
	   		yyval.dir 	= tmp;
	   		yyval.cod 	= yyvsp[0].lexema;
	   ;
    break;}
case 54:
#line 385 "plp5.y"
{
	   		int tmp 	= NTemp();
	   		yyval.tipo = REAL;
	   		yyval.dir 	= tmp;
	   		yyval.cod 	= yyvsp[0].lexema;
	   ;
    break;}
case 55:
#line 391 "plp5.y"
{
	   		int tmp 	= NTemp();
	   		yyval.tipo = BOOLEANO;
	   		yyval.dir 	= tmp;
	   		yyval.cod 	= "0";
	   ;
    break;}
case 56:
#line 397 "plp5.y"
{
	   		int tmp = NTemp();
	   		yyval.tipo = BOOLEANO;
	   		yyval.dir 	= tmp;
	   		yyval.cod 	= "1";
	   ;
    break;}
case 57:
#line 403 "plp5.y"
{

	   ;
    break;}
case 58:
#line 406 "plp5.y"
{

	   ;
    break;}
case 59:
#line 409 "plp5.y"
{

	   ;
    break;}
case 60:
#line 413 "plp5.y"
{
  
  //$$.tipo = buscarTipo($1.lexema);
  int tmp = NTemp();
  yyval.dir = tmp;
  yyval.dBase = buscarDir(yyvsp[0].lexema);
  yyval.cod = "mov #0 " + tmp;

;
    break;}
case 61:
#line 422 "plp5.y"
{if(esBase(yyvsp[-1].tipo)) msgError(1,1,1,"");;
    break;}
case 62:
#line 423 "plp5.y"
{
      if(!esBase(yyvsp[-1].tipo)){ msgError(ERR_EXP_ENT,1,1,"");}
      else{
        yyval.tipo = tipoBase(yyvsp[-4].tipo);
        int tmp = NTemp();
        yyval.dir = tmp;
        yyval.dBase = yyvsp[-4].dBase;
        yyval.cod = yyvsp[-4].cod + yyvsp[-1].cod + "mov #" + tamTipo(yyvsp[-4].tipo) + "\naddi " + yyvsp[-1].dir + "\nmov A " + tmp;
      }

  ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 436 "plp5.y"

bool esBase(int tipo)
{
  if(tipo <= 3)
    return true;
  else return false;
}

//Funcion del profesor
void msgError(int nerror,int nlin,int ncol,const char *s)
{

     switch (nerror) {
         case ERRLEXICO: fprintf(stderr,"Error lexico (%d,%d): caracter '%s' incorrecto\n",nlin,ncol,s);
            break;
         case ERRSINT: fprintf(stderr,"Error sintactico (%d,%d): en '%s'\n",nlin,ncol,s);
            break;
         case ERREOF: fprintf(stderr,"Error sintactico: fin de fichero inesperado\n");
            break;
         case ERRLEXEOF: fprintf(stderr,"Error lexico: fin de fichero inesperado\n");
            break;
         default:
            fprintf(stderr,"Error semantico (%d,%d): ", nlin,ncol);
            switch(nerror) {
             case ERRYADECL: fprintf(stderr,"simbolo '%s' ya declarado\n",s);
               break;
             case ERRNODECL: fprintf(stderr,"identificador '%s' no declarado\n",s);
               break;
             case ERR_NOSC: fprintf(stderr,"identificador '%s' no es un Scanner\n",s);
               break;
             case ERR_SCVAR: fprintf(stderr,"identificador '%s' es de tipo Scanner\n",s);
               break;
             case ERR_TIPOSDECLARRAY: fprintf(stderr,"los tipos deben ser iguales en la declaracion del array '%s'\n",s);
               break;
             case ERR_DIMSDECLARRAY: fprintf(stderr,"las dimensiones deben ser iguales en la declaracion del array '%s'\n",s);
               break;
             case ERRDIM: fprintf(stderr,"la dimension debe ser mayor que cero\n");
               break;
             case ERR_TIPOSASIG: fprintf(stderr,"tipos incompatibles en asignacion\n");
               break;
             case ERR_TIPOS: fprintf(stderr,"tipos incompatibles en '%s'\n",s);
               break;
             case ERR_TIPOSIFW: fprintf(stderr,"la expresion de if/while debe ser booleana\n");
               break;
             case ERR_OPNOBOOL: fprintf(stderr,"los operandos deben ser booleanos\n");
               break;
             case ERR_NUM: fprintf(stderr,"los operandos deben ser numericos\n");
               break;
             case ERRFALTAN: fprintf(stderr,"faltan indices\n");
               break;
             case ERRSOBRAN: fprintf(stderr,"sobran indices\n");
               break;
             case ERR_EXP_ENT: fprintf(stderr,"la expresion entre corchetes debe ser de tipo entero\n");
               break;

             case ERR_NOCABE:fprintf(stderr,"la variable '%s' ya no cabe en memoria\n",s);
               break;
             case ERR_MAXVAR:fprintf(stderr,"en la variable '%s', hay demasiadas variables declaradas\n",s);
               break;
             case ERR_MAXTIPOS:fprintf(stderr,"hay demasiados tipos definidos\n");
               break;
             case ERR_MAXTMP:fprintf(stderr,"no hay espacio para variables temporales\n");
               break;
            }
        }
     exit(1);
}

int yyerror(char *s)
{
    extern int findefichero;   //  variable definida en plp5.l que indica si
                               // se ha acabado el fichero
    if (findefichero) 
    {
       msgError(ERREOF,-1,-1,"");
    }
    else
    {  
       msgError(ERRSINT,nlin,ncol-strlen(yytext),yytext);
    }
}

void crear_ambito(const char* nombre)
{
	struct tabla_simbolos_t* nuevo_ambito = (tabla_simbolos_t*)calloc(1, sizeof(struct tabla_simbolos_t));
	nuevo_ambito->ts_padre = ambito;
	nuevo_ambito->nombre = nombre;
	ambito = nuevo_ambito; 
}



void nuevoSimbolo(simbolo_t& simbolo, const int& tipo) { 

  toLower(simbolo.lexema);

  if(!existeSimbolo(simbolo.lexema))  // Si no existe
  {
    simbolo_t s;
    tipo_t obj_tipo;
    
    if(buscarTipo(tipo, obj_tipo))
    {
      //s.size = obj_tipo.size;
    }
    else
    {
      /* CREAR NUEVO TIPO */
    }
    

    s.lexema    = simbolo.lexema;
    s.tipo      = tipo;
    s.lin       = simbolo.lin;
    s.col       = simbolo.col;
    s.dir       = ptr_mem;
    s.idTipo  = simbolo.idTipo;
    s.esArray  = simbolo.esArray;
    // asignamos la relacion del tipo con la tabla de tipos
    if(!s.esArray){
      switch(tipo)
      {
        case ENTERO: 
          s.idTipo = 0;
          break;
        case REAL:
          s.idTipo = 1;
          break;
        case BOOLEANO:
          s.idTipo = 2;
          break;
        case SCANNER:
          s.idTipo = 3;
          break;
      }     
    }


    ptr_mem += obj_tipo.size;

    if(ptr_mem > MAX_MEM)   // Si no cabe en memoria..
      msgError(ERR_NOCABE, simbolo.lin, simbolo.col, simbolo.lexema.c_str());    // error, memoria llena  

    simbolos.push_back(s);
  }
  else
    msgError(ERRYADECL, simbolo.lin, simbolo.col, simbolo.lexema.c_str());   // Error, simbolo ya declarado
  
}

bool existeSimbolo(string& simbolo) {
  toLower(simbolo);
  std::vector<simbolo_t>::iterator begin_it = simbolos.begin();
  std::vector<simbolo_t>::iterator end_it   = simbolos.end();
  std::vector<simbolo_t>::iterator it       = std::find_if(begin_it,end_it, find_simbolo(simbolo)); 

  return it != end_it;
}

bool buscarSimbolo(simbolo_t& simbolo) {    // simbolo debe llegar con el lexema y volvera con todos los atributos
  toLower(simbolo.lexema);
  std::vector<simbolo_t>::iterator begin_it = simbolos.begin();
  std::vector<simbolo_t>::iterator end_it   = simbolos.end();
  std::vector<simbolo_t>::iterator it       = std::find_if(begin_it,end_it, find_simbolo(simbolo.lexema)); 

  if(it != end_it)
  {
    simbolo.tipo  = it->tipo;
    simbolo.dir   = it->dir;

    #if DEBUG_MODE
      cout << "buscarSimbolo --> Dir: " << simbolo.dir << "\tTipo: "<< simbolo.tipo << "\n";
    #endif

    return true;
  }
  return false;
} 

int getDir() {
	return 1;
}

int NTemp(){
	nTempActual ++; 
	if(nTempActual >= nTempMax)
		msgError(ERR_MAXTMP, nlin, ncol, "") ;
	else return nTempActual;
}

bool buscarTipo(int tipo_buscado, tipo_t& t) {
  std::vector<tipo_t>::iterator it_tipos;

#if DEBUG_MODE == 2
  cout << "Buscando tipo " << tipo_buscado << "...\n";
#endif

  for(it_tipos = tabla_tipos.begin(); it_tipos != tabla_tipos.end(); ++it_tipos)
  {
    if(it_tipos->tipo == tipo_buscado)
    {
      t.tipo      = it_tipos->tipo;
      t.size      = it_tipos->size;
      t.tipo_base = it_tipos->tipo_base;

      return true;
    }
  }
  return false;
}

void inicializarTablaTipos() {
  tipo_t t;
  tabla_tipos.clear();

  t.tipo      = ENTERO;
  t.size      = TAM_ENTERO;
  t.tipo_base = -1;
  tabla_tipos.push_back(t);

  t.tipo      = REAL;
  t.size      = TAM_REAL;
  t.tipo_base = -1;
  tabla_tipos.push_back(t);

  t.tipo      = BOOLEANO;
  t.size      = TAM_BOOLEANO;
  t.tipo_base = -1;
  tabla_tipos.push_back(t);

  t.tipo      = SCANNER;
  t.size      = TAM_SCANNER;
  t.tipo_base = -1;
  tabla_tipos.push_back(t);
}

void print_tabla_tipos() {
  std::vector<tipo_t>::iterator it_tipos;
  int pos = 0;
  std::cout << "############ TABLA DE TIPOS ############\n";

  for(it_tipos = tabla_tipos.begin(); it_tipos != tabla_tipos.end(); ++it_tipos)
  {
    cout << "Pos: " << pos << 
            "\tTipo: " << it_tipos->tipo << 
            "\tTam: " << it_tipos->size <<
            "\tT.Base: " << it_tipos->tipo_base << "\n";
    ++pos;
  }
  std::cout << "########################################\n";

}

void print_tabla_simbolos() {
  std::cout << "############ TABLA DE SIMBOLOS ############\n";
  std::vector<simbolo_t>::iterator it_simbolos;
  int pos = 0;
  for(it_simbolos = simbolos.begin(); it_simbolos != simbolos.end(); ++it_simbolos)
  {
    cout << "Pos.: " << pos << 
    "\tSimbolo: " << it_simbolos->lexema << 
    "\tTipo: " << it_simbolos->tipo << 
    "\tIdx.Tipo: " << it_simbolos->idTipo << 
    "\tDir.: " << it_simbolos->dir <<
    "\tArray? " << it_simbolos->esArray << "\n";
    ++pos;
  }
  std::cout << "###########################################\n";
}

void nuevoTipo(const int& tam, const int& tipo_base) {
  tipo_t t;
  switch(tipo_base)
  {
    case ENTERO: 
      t.tipo_base = 0;
      break;
    case REAL:
      t.tipo_base = 1;
      break;
    case BOOLEANO:
      t.tipo_base = 2;
      break;
    case SCANNER:
      t.tipo_base = 3;
      break;
    default:
      t.tipo_base = tipo_base;
      break;
  }
  t.tipo    = ARRAY;
  t.size    = tam;
  tabla_tipos.push_back(t);
}

void toLower(string& str)
{
  for(int i = 0; i < str.size(); i++)
  {
    str[i] = tolower(str[i]);
  }
}

void destruir_ambito_actual()
{
	struct tabla_simbolos_t* padre;
	padre = ambito->ts_padre;
	free(ambito);
	ambito = padre;
	padre = NULL;
}

void destroy()
{
	struct tabla_simbolos_t* next;
	while(ambito != NULL)
	{
		next = ambito->ts_padre;
		free(ambito);
		ambito = next;
	}
	next = NULL;

}

int main(int argc,char *argv[])
{
    FILE *fent;

    if (argc==2)
    {
        fent = fopen(argv[1],"rt");
        if (fent)
        {
        	crear_ambito("global");
            yyin = fent;
            yyparse();
            fclose(fent);
        }
        else
            fprintf(stderr,"No puedo abrir el fichero\n");
    }
    else
        fprintf(stderr,"Uso: ejemplo <nombre de fichero>\n");
}